// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnNg5c2HtOH4aBMtQtJw7GnwrAXdG4U7o',
    appId: '1:841062329285:web:063c4c263c0f9ed176f9ac',
    messagingSenderId: '841062329285',
    projectId: 'hotelapp-c85b4',
    authDomain: 'hotelapp-c85b4.firebaseapp.com',
    storageBucket: 'hotelapp-c85b4.firebasestorage.app',
    measurementId: 'G-F6V8CJCRPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWdvdz5YbKdgGmLLhGhHv6uwQ3Pc5vurQ',
    appId: '1:841062329285:android:beaa675321b1fb7976f9ac',
    messagingSenderId: '841062329285',
    projectId: 'hotelapp-c85b4',
    storageBucket: 'hotelapp-c85b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMH4qOsLIU4f0yoyN6GJ5AYZJNdpdV8Dc',
    appId: '1:841062329285:ios:7fe2c10502c706a676f9ac',
    messagingSenderId: '841062329285',
    projectId: 'hotelapp-c85b4',
    storageBucket: 'hotelapp-c85b4.firebasestorage.app',
    androidClientId: '841062329285-hkp7eidqu7p21bjnp6pbaoikefosgt5s.apps.googleusercontent.com',
    iosClientId: '841062329285-0902prdugqsrfneulkjsm5gghdncj6do.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMH4qOsLIU4f0yoyN6GJ5AYZJNdpdV8Dc',
    appId: '1:841062329285:ios:7fe2c10502c706a676f9ac',
    messagingSenderId: '841062329285',
    projectId: 'hotelapp-c85b4',
    storageBucket: 'hotelapp-c85b4.firebasestorage.app',
    androidClientId: '841062329285-hkp7eidqu7p21bjnp6pbaoikefosgt5s.apps.googleusercontent.com',
    iosClientId: '841062329285-0902prdugqsrfneulkjsm5gghdncj6do.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnNg5c2HtOH4aBMtQtJw7GnwrAXdG4U7o',
    appId: '1:841062329285:web:616d6271ce3d3f0e76f9ac',
    messagingSenderId: '841062329285',
    projectId: 'hotelapp-c85b4',
    authDomain: 'hotelapp-c85b4.firebaseapp.com',
    storageBucket: 'hotelapp-c85b4.firebasestorage.app',
    measurementId: 'G-RKTLMC9C1S',
  );
}
